# maria db instance
db:
  build: ./db
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=test

# api flask app
api:
  image: xanderblr/kicker-scorer-api:latest
  ports:
    - "8000:8000"
  links:
    - db

# angular SPA
ui:
  image: xanderblr/kicker-scorer-ui:latest

# nginx gateway
web:
  build: ./web
  ports:
    - "80:80"
  links:
    - api
  volumes_from:
    - api
    - ui
