# maria db instance
db:
  build: ./db
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=test

# api flask app code (volume container)
api:
  image: xanderblr/kicker-scorer-api:latest

# python runtime
uwsgi:
  build: ./uwsgi
  ports:
    - "8001:8001"
  volumes_from:
    - api
  links:
    - db

# angular SPA (volume container)
ui:
  image: xanderblr/kicker-scorer-ui:latest

# nginx gateway
web:
  build: ./web
  ports:
    - "80:80"
  links:
    - uwsgi
  volumes_from:
    - uwsgi
    - ui
